# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Generate config file

on:
  push:
    branches:
      - 'main'
    paths:
      - 'meme/*'

jobs:
  generate-config-file:
    name: Generate config file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: build config
        run: |
          chmod +x ./shell/computed.sh
          ./shell/computed.sh
          cat static/scripts/config.js
          git add static/scripts/config.js
      - uses: stefanzweifel/git-auto-commit-action@v2.3.0
        with:
          commit_message: 'chore: update config file'
          branch: ${{ github.ref_name }}
          file_pattern: meme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
